# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20180723_2220'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='comment',
    #         name='article_id',
    #         field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='learn.Article'),
    #     ),
    # ]
